### ISSUE TITLE
cudaMalloc de-reference fix 

### ISSUE THREAD

**Issue by msharmavikram** [cwpearson/dnn#10]
cudaMalloc memory pointers need to have (void **).

**Comment by cwpearson** [comment]
Like here?

https://github.com/cwpearson/dnn/blob/d61c0f40b6df56f8dc81de825e8347db7984e717/src/cuda_malloc.hpp#L9

**Comment by msharmavikram** [comment]
Yes. All the cudamalloc definition. It was giving run time error. After this change, it worked for me.
